### ISSUE TITLE
Error uploading video

### ISSUE THREAD

**Issue by harminoff** [offish/opplast#25]
Hello! Thanks for creating this!

I look to be getting this error when using Upload. It does upload the video, but doesn't publish

DEBUG: Trying to set "...." as description...
Error:  Message: Unable to locate element: /html/body/ytcp-uploads-dialog/tp-yt-paper-dialog/div/ytcp-animatable[1]/ytcp-video-metadata-editor/div/ytcp-video-metadata-editor-basics/div[2]/ytcp-mention-textbox/ytcp-form-input-container/div[1]/div[2]/ytcp-mention-input

**Comment by LittleTerry** [comment]
same here, when it comes to set description, it reports:

Unable to locate element: /html/body/ytcp-uploads-dialog/tp-yt-paper-dialog/div/ytcp-animatable[1]/ytcp-video-metadata-editor/div/ytcp-video-metadata-editor-basics/div[2]/ytcp-mention-textbox/ytcp-form-input-container/div[1]/div[2]/ytcp-mention-input

any idea?

**Comment by harminoff** [comment]
In constants, updating DESCRIPTION CONTAINER to 

DESCRIPTION_CONTAINER = '/html/body/ytcp-uploads-dialog/tp-yt-paper-dialog/div/ytcp-animatable[1]/ytcp-video-metadata-editor/div/ytcp-video-metadata-editor-basics/div[2]/ytcp-social-suggestions-textbox/ytcp-form-input-container/div[1]/div[2]/ytcp-mention-input'

fixes it

**Comment by LittleTerry** [comment]
> In constants, updating DESCRIPTION CONTAINER to
> 
> DESCRIPTION_CONTAINER = '/html/body/ytcp-uploads-dialog/tp-yt-paper-dialog/div/ytcp-animatable[1]/ytcp-video-metadata-editor/div/ytcp-video-metadata-editor-basics/div[2]/ytcp-social-suggestions-textbox/ytcp-form-input-container/div[1]/div[2]/ytcp-mention-input'
> 
> fixes it

cool, it worlks! many thanks!

**Comment by offish** [comment]
I'll update it real soon
