### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@type='file']

### ISSUE THREAD

**Issue by SpookyToad2** [offish/opplast#26]
I'm experiencing this error. That's my script

from opplast import Upload

```
if __name__ == "__main__":
    upload = Upload(
        # use r"" for paths, this will not give formatting errors e.g. "/n"
        r"C:/Users/SpookyToad/AppData/Roaming/Mozilla/Firefox/Profiles/oysfbms4.selenium",
    )

    video_id = upload.upload(
        r"E:\mc_video\video.mp4",
        title="My YouTube Title",
        description="My YouTube Description",
        thumbnail=r"E:\mc_video\thumbnail.jpg",
        tags=["these", "are", "my", "tags"],
    )

    #if was_uploaded:
    #    print(f"{video_id} has been uploaded to YouTube")

    upload.close()
```

It says that error happens in script Upload at 80th line

        self.driver.find_element_by_xpath(INPUT_FILE_VIDEO).send_keys(get_path(file))
        sleep(self.timeout)

How i'm able to fix that?

**Comment by offish** [comment]
This error usually appears when the page takes too long to load, or YouTube is asking you for something. Run with `headless=False` and see what happens.

**Comment by SpookyToad2** [comment]
Okay good news. I've fixed it by installing older version of firefox. Thanks for your fast response!
