### ISSUE TITLE
Unable to find clips for specific streamers

### ISSUE THREAD

**Issue by OfficiallySp** [offish/opplast#27]
The script cannot find clips from a certain streamer despite other streamers working fine

![image](https://user-images.githubusercontent.com/46799448/149006231-19cbb2ff-4b45-4487-ad50-49896bef4fba.png)
![image](https://user-images.githubusercontent.com/46799448/149006262-65904e3b-b6da-4472-9cb5-1a0ce9ca7de9.png)

the config file is completely stock except for length which is 10 minutes and timeframe which is set to 0 (all time)

**Comment by Smokof** [comment]
Hi, One year later i'm working on this script and had the same trouble, the issue was about the language of the streamer, was looking for ES clips and the streamer was by default in EN
